Algoritmo "21-03-23_ex-1-2"

Var

  nomes:vetor[0..4] de caractere
  contador:inteiro

Inicio

      para  contador de 0 ate 4  faça
         escreval(" Digite um nome: ")
          leia(nomes[contador])
      fimpara
  limpatela
      para  contador de 0 ate 4  faça
         escreval(nomes[contador]," ")
      fimpara
      para  contador de 0 ate 0  faça
         escreval(nomes[0]," ",nomes[4])
      fimpara
Fimalgoritmo